services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: micro_hub_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: micro_hub_prod
      JWT_SECRET: your-production-jwt-secret
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres_data:
