/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { type CoreButtonCustomEvent, type CoreInputCustomEvent, type Event } from "@felipemalli-libs/microhub-ui";
import { CoreButton as CoreButtonElement } from "@felipemalli-libs/microhub-ui/dist/components/core-button.js";
import { CoreInput as CoreInputElement } from "@felipemalli-libs/microhub-ui/dist/components/core-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
export type CoreButtonEvents = {
    onCoreClick: EventName<CoreButtonCustomEvent<MouseEvent>>;
};
export declare const CoreButton: StencilReactComponent<CoreButtonElement, CoreButtonEvents>;
export type CoreInputEvents = {
    onCoreInput: EventName<CoreInputCustomEvent<Event>>;
    onCoreChange: EventName<CoreInputCustomEvent<Event>>;
    onCoreFocus: EventName<CoreInputCustomEvent<FocusEvent>>;
    onCoreBlur: EventName<CoreInputCustomEvent<FocusEvent>>;
};
export declare const CoreInput: StencilReactComponent<CoreInputElement, CoreInputEvents>;
