/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { type CoreButtonCustomEvent } from "@felipemalli-libs/microhub-ui";
import { CoreButton as CoreButtonElement } from "@felipemalli-libs/microhub-ui/dist/components/core-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
export type CoreButtonEvents = {
    onCoreClick: EventName<CoreButtonCustomEvent<MouseEvent>>;
};
export declare const CoreButton: StencilReactComponent<CoreButtonElement, CoreButtonEvents>;
