'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type CoreButtonCustomEvent } from "@felipemalli-libs/microhub-ui";
import { CoreButton as CoreButtonElement, defineCustomElement as defineCoreButton } from "@felipemalli-libs/microhub-ui/dist/components/core-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type CoreButtonEvents = { onCoreClick: EventName<CoreButtonCustomEvent<MouseEvent>> };

export const CoreButton: StencilReactComponent<CoreButtonElement, CoreButtonEvents> = /*@__PURE__*/ createComponent<CoreButtonElement, CoreButtonEvents>({
    tagName: 'core-button',
    elementClass: CoreButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCoreClick: 'coreClick' } as CoreButtonEvents,
    defineCustomElement: defineCoreButton
});
