/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoreButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'danger';
    }
}
export interface CoreButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCoreButtonElement;
}
declare global {
    interface HTMLCoreButtonElementEventMap {
        "coreClick": MouseEvent;
    }
    interface HTMLCoreButtonElement extends Components.CoreButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCoreButtonElementEventMap>(type: K, listener: (this: HTMLCoreButtonElement, ev: CoreButtonCustomEvent<HTMLCoreButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCoreButtonElementEventMap>(type: K, listener: (this: HTMLCoreButtonElement, ev: CoreButtonCustomEvent<HTMLCoreButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCoreButtonElement: {
        prototype: HTMLCoreButtonElement;
        new (): HTMLCoreButtonElement;
    };
    interface HTMLElementTagNameMap {
        "core-button": HTMLCoreButtonElement;
    }
}
declare namespace LocalJSX {
    interface CoreButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onCoreClick"?: (event: CoreButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'danger';
    }
    interface IntrinsicElements {
        "core-button": CoreButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-button": LocalJSX.CoreButton & JSXBase.HTMLAttributes<HTMLCoreButtonElement>;
        }
    }
}
